window._w= {};

window._w.alegeri = {
    "Prezidentiale 2019": "prezidentiale2019",
    "Europarlamentare 2019": "europarlamentare2019",
    "Primari 2020": "locale27092020P",
    "Parlamentare CD 2020": "parlamentare06122020CD",
    "Parlamentare Senat 2020": "parlamentare06122020S",
    "Primari 2024": "locale09062024P",
    "primari Noi2024": "primariNoi",
    "Consiliu Local 2024": "locale09062024CL",
    "Consiliu Judetean 2024": "locale09062024CJ",
    "Presedinte C.J. 2024": "locale09062024PCJ",
    "Europarlamentare 2024": "europarlamentare09062024EUP",
    "Prezidentiale Tur 1 2024": "prezidentiale1_24112024"
}
window._w.prezenta = {
    "parlamentare 2020": "parlamentare06122020",
    "locale2020": "locale27092020",
    "locale2024": "locale09062024",
    "europarlamentare2024": "europarlamentare09062024",
    "prezidentiale Tur 1 2024": "prezidentiale1_24112024_HOURLY",
    "parlamentare2024": "parlamentare01122024",
}

window._w.countiesName = {
    "AB": "ALBA",
    "AR": "ARAD",
    "AG": "ARGES",
    "BC": "BACAU",
    "BH": "BIHOR",
    "BN": "BISTRITA-NASAUD",
    "BT": "BOTOSANI",
    "BR": "BRAILA",
    "BV": "BRASOV",
    "BZ": "BUZAU",
    "CL": "CALARASI",
    "CS": "CARAS-SEVERIN",
    "CJ": "CLUJ",
    "CT": "CONSTANTA",
    "CV": "COVASNA",
    "DB": "DAMBOVITA",
    "DJ": "DOLJ",
    "GL": "GALATI",
    "GR": "GIURGIU",
    "GJ": "GORJ",
    "HR": "HARGHITA",
    "HD": "HUNEDOARA",
    "IL": "IALOMITA",
    "IS": "IASI",
    "IF": "ILFOV",
    "MM": "MARAMURES",
    "MH": "MEHEDINTI",
    "B": "BUCURESTI",
    "S1": "BUCURESTI SECTORUL 1",
    "S2": "BUCURESTI SECTORUL 2",
    "S3": "BUCURESTI SECTORUL 3",
    "S4": "BUCURESTI SECTORUL 4",
    "S5": "BUCURESTI SECTORUL 5",
    "S6": "BUCURESTI SECTORUL 6",
    "MS": "MURES",
    "NT": "NEAMT",
    "OT": "OLT",
    "PH": "PRAHOVA",
    "SJ": "SALAJ",
    "SM": "SATU MARE",
    "SB": "SIBIU",
    "SR": "STRAINATATE",
    "SV": "SUCEAVA",
    "TR": "TELEORMAN",
    "TM": "TIMIS",
    "TL": "TULCEA",
    "VL": "VALCEA",
    "VS": "VASLUI",
    "VN": "VRANCEA",
    "CO": "CORESPONDENTA"
};
window._w.countiesCodes = Object.fromEntries(Object.entries(window._w.countiesName).map(([key, value]) => [value, key]));
window._w.partide = [
    { match: /(USR|UNIUNEA SALVA.I ROM.NIA|Lasconi)/i, fill: "#00b2ff" },
    { match: /\b(PSD PNL)\b/i, fill: "#ff5100" },
    { match: /\b(PNL|PARTIDUL NATIONAL LIBERAL|KLAUS|CIUCA)\b/i, fill: "#ffc300" },
    { match: /\b(PSD|PARTIDUL SOCIAL DEMOCRAT|DANCILA|CIOLACU)\b/i, fill: "#ff001e" },
    { match: /\b(AUR|ALIANTA PENTRU UNIREA ROMANILOR|SIMION)\b/i, fill: "#A16800" },
    { match: /\b(CALIN GEORGESCU)\b/i, fill: "#AC4959" },
    { match: /\b(UDMR|MAGHIAR|KELEMEN)/i, fill: "#1ED760" },
    { match: /(ALIAN.A MAGHIAR.A)/i, fill: "#2e821b" },
    { match: /\b(PMP|MISCAREA POPULARA)\b/i, fill: "#6542B1" },
    { match: /(PRO ROMANIA|^PRO)\b/i, fill: "#e16bff" },
    { match: /\b(INDEPENDENT)\b/i, fill: "#394d4d" },
    { match: /\b(PROIECTUL EUROPEAN)\b/i, fill: "#C62979" },
    { match: /\b(S\.O\.S)\b/i, fill: "#F8B7C0" },
    { match: /\b(CMM|ALIANTA PENTRU )\b/i, fill: "#154066" },
    { match: /\b(ALDE|ALIANTA LIBERALILOR)\b/i, fill: "#534d82" },
    { match: /\b(ALIAN.A SOCIAL LIBERALA)\b/i, fill: "#333331" },
    { match: /\b(ALIAN.A PENTRU UNIREA ROMANILOR)\b/i, fill: "#C5A655" }
];
window._w.results = {};
let customColors = [
    "#0B84A5",
    "#F6C85F",
    "#6F4E7C",
    "#9DD866",
    "#CA472F",
    "#FFA056",
    "#8DDDD0",
    "#ffa600",
    "#003f5c",
    "#2f4b7c",
    "#665191",
    "#a05195",
    "#d45087",
    "#f95d6a",
    "#ff7c43",
];
let lastColor = 0;
let customCandidates = {};
function getPartyColor(party) {
    if (!party) return "#878787";
    party = party.clear();
    return window._w.partide.find(colors => party.match(colors.match))?.fill || 
        (customCandidates[party] || (customCandidates[party] = customColors[lastColor++ % customColors.length]));
}
window._w.countries = {
    "ZAF": "AFRICA DE SUD",
    "ALB": "REPUBLICA ALBANIA",
    "DZA": "ALGERIA",
    "AGO": "ANGOLA",
    "SAU": "REGATUL ARABIEI SAUDITE",
    "ARG": "ARGENTINA",
    "ARM": "ARMENIA",
    "AUS": "AUSTRALIA",
    "NZL": "NOUA ZEELANDA",
    "AUT": "AUSTRIA",
    "AZE": "AZERBAIDJAN",
    "BLR": "REPUBLICA BELARUS",
    "BEL": "BELGIA",
    "BIH": "BOSNIA SI HERTEGOVINA",
    "BRA": "BRAZILIA",
    "BGR": "BULGARIA",
    "CAN": "CANADA",
    "CZE": "REPUBLICA CEHA",
    "CHL": "CHILE",
    "CHN": "REPUBLICA POPULARA CHINEZA",
    "CYP": "REPUBLICA CIPRU",
    "COL": "REPUBLICA COLUMBIA",
    "KOR": "REPUBLICA COREEA",
    "HRV": "REPUBLICA CROATIA",
    "CUB": "CUBA",
    "DNK": "DANEMARCA",
    "EGY": "EGIPT",
    "CHE": "ELVETIA",
    "ARE": "EMIRATELE ARABE UNITE",
    "EST": "ESTONIA",
    "ETH": "ETIOPIA",
    "PHL": "FILIPINE",
    "FIN": "FINLANDA",
    "FRA": "FRANTA",
    "MCO": "PRINCIPATUL MONACO",
    "GEO": "GEORGIA",
    "DEU": "GERMANIA",
    "GRC": "REPUBLICA ELENA",
    "IND": "REPUBLICA INDIA",
    "IDN": "REPUBLICA INDONEZIA",
    "JOR": "REGATUL HASEMIT AL IORDANIEI",
    "IRQ": "IRAK",
    "IRN": "REPUBLICA ISLAMICA IRAN",
    "IRL": "IRLANDA",
    "ISL": "ISLANDA",
    "ISR": "STATUL ISRAEL",
    "ITA": "ITALIA",
    "JPN": "JAPONIA",
    "KAZ": "KAZAHSTAN",
    "KEN": "KENYA",
    "KWT": "KUWEIT",
    "LBN": "REPUBLICA LIBANEZA",
    "LTU": "LITUANIA",
    "LVA": "LETONIA",
    "LUX": "LUXEMBURG",
    "MKD": "REPUBLICA MACEDONIA DE NORD",
    "MYS": "MALAYSIA",
    "MLT": "MALTA",
    "GBR": "REGATUL UNIT AL MARII BRITANII SI AL IRLANDEI DE NORD",
    "MAR": "REGATUL MAROC",
    "MEX": "MEXIC",
    "MDA": "REPUBLICA MOLDOVA",
    "MNE": "MUNTENEGRU",
    "NGA": "REPUBLICA FEDERALA NIGERIA",
    "NOR": "NORVEGIA",
    "NLD": "REGATUL TARILOR DE JOS",
    "OMN": "SULTANATUL OMAN",
    "PAK": "REPUBLICA ISLAMICA PAKISTAN",
    "PSE": "PALESTINA",
    "PER": "REPUBLICA PERU",
    "POL": "POLONIA",
    "PRT": "PORTUGALIA",
    "QAT": "QATAR",
    "RUS": "FEDERATIA RUSA",
    "SEN": "SENEGAL",
    "SRB": "REPUBLICA SERBIA",
    "SGP": "REPUBLICA SINGAPORE",
    "SYR": "REPUBLICA ARABA SIRIANA",
    "SVK": "REPUBLICA SLOVACA",
    "SVN": "SLOVENIA",
    "ESP": "SPANIA",
    "LKA": "SRI LANKA",
    "USA": "STATELE UNITE ALE AMERICII",
    "SWE": "SUEDIA",
    "THA": "REGATUL THAILANDEI",
    "TUN": "REPUBLICA TUNISIANA",
    "TUR": "TURCIA",
    "TKM": "TURKMENISTAN",
    "UKR": "UCRAINA",
    "HUN": "UNGARIA",
    "URY": "REPUBLICA ORIENTALA A URUGUAYULUI",
    "UZB": "UZBEKISTAN",
    "VNM": "REPUBLICA SOCIALISTA VIETNAM",
    "ZWE": "ZIMBABWE",
    "TZA": "TANZANIA"
};
window._w.countriesCode = Object.fromEntries(Object.entries(window._w.countries).map(([key, value]) => [value, key]));

const mapTiles = [
    { name: 'cartoDB Light', url: 'https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png' },
    { name: 'cartoDB Dark', url: 'https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png' },
    { name: 'OSM Terrain', url: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png' },
    { name: 'ESRI', url: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}' },
    { name: 'OpenTopoMap', url: 'https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png' }
];
String.prototype.clear = function () {
    return this.replace(/î/g, 'a')
        .replace(/Î/g, 'I')
        .normalize("NFD")
        .replace(/[\u0300-\u036f]/g, "")
        .toUpperCase()
        .replace(/(MUNICIPIUL|ORAS) ?/ig, '')
        .replace(/\. /ig, '.')
        .replace(/ - /ig, '-')
        ;
}